[env:seeed_xiao_esp32c3]
platform = espressif32 @ 6.6.0
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
upload_speed = 115200

build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DAUTOCONNECT_NO_FS
    -DAUTOCONNECT_USE_WEBSERVER

lib_deps = 
    Hieromon/AutoConnect @ ^1.4.2
    bblanchon/ArduinoJson @ ^6.21.5